const express=require('express');
const formControl=require('../controller/formControl');
const hostController = require('../controller/hostController');
const path = require('path');
const rootdir=require('../util/path');
const formRouter=express.Router();
const bodyParser = require('body-parser');
formRouter.use(bodyParser.urlencoded({ extended: true }));
formRouter.get("/form",formControl.getaddForm);
formRouter.post("/form",formControl.postForm);
formRouter.get("/edit-home/:id", hostController.geteditForm);
formRouter.post("/edit-home", hostController.posteditForm);
exports.router=formRouter;